-- GENERATED by `npm run db:bundle` from supabase/migrations. Do not edit by hand.
-- Paste into Supabase → SQL Editor → Run, once, on a fresh project.

begin;

-- ===== 20261001000000_create_user_profiles.sql =====

-- user_profiles: one row per auth user. RLS is mandatory for every table.

create table public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) between 2 and 50),
  avatar_url text,
  bio text check (char_length(bio) <= 280),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;
alter table public.user_profiles force row level security;

create policy "user_profiles_select_own"
  on public.user_profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "user_profiles_insert_own"
  on public.user_profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy "user_profiles_update_own"
  on public.user_profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- No delete policy: rows are removed only via the auth.users cascade.

-- Keep updated_at current.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger user_profiles_set_updated_at
  before update on public.user_profiles
  for each row execute function public.set_updated_at();

-- Create a profile automatically when a user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_profiles (id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===== 20261001000100_create_warranty_registrations.sql =====

-- warranty_registrations: one row per activated product warranty. RLS is mandatory.

create table public.warranty_registrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  product_name text not null check (char_length(product_name) between 2 and 100),
  serial_number text not null unique check (serial_number ~ '^[A-Z0-9-]{6,40}$'),
  purchase_date date not null check (
    purchase_date <= current_date + 1
    and purchase_date >= current_date - interval '5 years'
  ),
  retailer text check (char_length(retailer) <= 100),
  -- Set by the database, never by the client (see column grants below).
  warranty_months smallint not null default 12 check (warranty_months between 1 and 120),
  expires_on date generated always as (
    (purchase_date + warranty_months * interval '1 month')::date
  ) stored,
  activated_at timestamptz not null default now()
);

create index warranty_registrations_user_id_idx on public.warranty_registrations (user_id);

alter table public.warranty_registrations enable row level security;
alter table public.warranty_registrations force row level security;

create policy "warranty_registrations_select_own"
  on public.warranty_registrations for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "warranty_registrations_insert_own"
  on public.warranty_registrations for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- No update/delete policies: an activated warranty is immutable for the owner.

-- Column-level privileges: clients may only supply these four columns.
-- user_id comes from auth.uid(); warranty_months and timestamps from defaults.
revoke all on public.warranty_registrations from anon, authenticated;
grant select on public.warranty_registrations to authenticated;
grant insert (product_name, serial_number, purchase_date, retailer)
  on public.warranty_registrations to authenticated;

commit;
